### ISSUE TITLE
ERROR: unsupported cyclic timeseries when running the wflow model in Julia language

### ISSUE THREAD

**Issue by arsalansaghir1** [Deltares/hydromt_wflow#159] opened 2023-03-10 05:41 UTC
I prepared the input files required for wflow simulation using hydromt_wflow plugin. I downloaded the data from several data sources and prepared the input files.
But when I run the simulation in Wflow I get the following error (attached below):

ERROR: unsupported cyclic timeseries
![Screenshot 2023-03-09 234006](https://user-images.githubusercontent.com/127018672/224233025-2ff390d6-03d7-4738-bc8b-086cfdd5ed63.jpg)

Why I'm getting this error?
I'm attaching the log file for both hydromt_wflow and Julia below.

[log.txt](https://github.com/Deltares/Wflow.jl/files/10934946/log.txt)
[hydromt.log](https://github.com/Deltares/Wflow.jl/files/10934947/hydromt.log)

Kindly guide me on how to proceed with this.

**Comment by verseve** [comment] 2023-03-10 07:34
This is a duplicate of issue https://github.com/Deltares/Wflow.jl/issues/247. Close this one since it is a Wflow issue.

**Closed by verseve** 2023-03-10 07:34 UTC
