### ISSUE TITLE
Bug: deriving basin in setup_basemaps does not work without basin_index_fn

### ISSUE THREAD

**Issue by arsalansaghir1** [Deltares/hydromt_wflow#156] opened 2023-03-05 09:59 UTC
I am currently trying to prepare the input files for my own region of interest. I have downloaded the data as per the specified links on the catalog but there was no link or instructions on how to prepare the "merit_hydro_index.gpkg" file. I tried preparing it myself on Qgis but I get the error:

"GeoDataFrame: No data within spatial domain C:\Users\Lenovo\Desktop\Analysis\wflow\artifactdata\merit_hydro_index.gpkg."

Can anyone guide me on how to proceed with this? 
I am attaching screenshots.
![Screenshot 2023-03-05 145906](https://user-images.githubusercontent.com/127018672/222953738-6350b038-c440-4633-97d3-5781edf17901.jpg)
![Screenshot 2023-03-05 145850](https://user-images.githubusercontent.com/127018672/222953742-f137c2ec-9a73-45db-99fc-4f6c64a6eef0.jpg)

**Comment by hboisgon** [comment] 2023-03-06 01:40
Hi @arsalansaghir1 thanks for posting your issue.
Indeed merit_hydro_index is a dataset that we created at Deltares. @DirkEilander do you think we can publish it or alternatively start using the merit_basins database instead? If so let's open an issue in hydromt repository.

Alternatively, I see you are providing ``bounds`` in your command line. The ``basin_index_fn`` argument of **setup_basemaps** is used to help hydromt with opening the right extent of merit_hydro to compute basin or subbasin boundaries (so not opening it for the whole world). But if you specify ``bounds`` then you should not need it per say. If you try again building your model  but with ``basin_index_fn = None`` does this work? Else I will open an issue because it should. Will anyway maybe improve the docs of **setup_basemaps** to make it more clear.

**Comment by arsalansaghir1** [comment] 2023-03-06 09:16
I tried building the model by specifying basin_index_fn = None but still facing the following error (attached below). Also I'm using this code to build the model:

!hydromt build wflow "./kaha_test" "{'subbasin': [29.13, 70.28], 'strord': 4, 'bounds': [29.09, 69.71, 30.14, 70.56]}" -r 0.00833 -i wflow_build.ini -d C:/Users/Lenovo/Desktop/Analysis/wflow/artifactdata/data_catalog.yml -vv 
![Screenshot 2023-03-06 141351](https://user-images.githubusercontent.com/127018672/223067391-395c28dd-7c13-4be7-b540-b9aa591a8fc7.jpg)

**Comment by hboisgon** [comment] 2023-03-06 09:57
Ok then we will pick this up hopefully for the next release. Will keep you updated via this issue.

**Comment by arsalansaghir1** [comment] 2023-03-06 09:59
What should I do for now in order to build the model? as it is quite essential for me to do modelling for my required area.

**Comment by arsalansaghir1** [comment] 2023-03-06 11:51
I did it as you suggested. Created a vector file based on the basins raster data from merit hydro 1k. But still facing the same error "No data found within spatial domain". Attaching screenshots.
![Screenshot 2023-03-06 164932](https://user-images.githubusercontent.com/127018672/223102500-f2ea1e2b-385f-4b38-af7e-60b3757794cb.jpg)
![Screenshot 2023-03-06 164908](https://user-images.githubusercontent.com/127018672/223102511-a3e72dfd-3d89-4f4c-8146-b2e50e4b3edb.jpg)

**Comment by hboisgon** [comment] 2023-03-07 05:40
Did you download merit_hydro for your region of interest? Or are you using the artifact data catalog which contains data for the Piave river only? From your screenshot I don't see which data catalog you are using or if no data within spatial domain error is caused by merit_hydro or merit_hydro_index data.
Else make sure the CRS are correct between your file and the data catalog.

**Comment by arsalansaghir1** [comment] 2023-03-07 06:01
I download the merit_hydro data for my own region of interest from the following link.
http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/index.html

I'm also facing this error now:
**ValueError: The flow direction type could not be inferred.**

I downloaded the flow direction tile from the above link. Do I have to process it for something?
![Uploading Screenshot 2023-03-07 110124.jpg…]()

**Comment by arsalansaghir1** [comment] 2023-03-07 06:02
I download the merit_hydro data for my own region of interest from the following link.
http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro/index.html

I'm also facing this error now:
ValueError: The flow direction type could not be inferred.

I downloaded the flow direction tile from the above link. Do I have to process it for something?
![Screenshot 2023-03-07 110124](https://user-images.githubusercontent.com/127018672/223334077-dcc754b0-efe2-4216-a432-85a3ce3ab0e1.jpg)

**Comment by hboisgon** [comment] 2023-03-07 06:04
Hum... @DirkEilander does this error ring a bell?

**Comment by arsalansaghir1** [comment] 2023-03-07 09:39
Hey can you also specify on how to change the variable names in netcdf files. I downloaded the nc data from modis and era5 but variables names are different. Do I have to change them manually? If so, can you recommend how to?

Thanks

**Comment by DirkEilander** [comment] 2023-03-07 14:30
> I tried building the model by specifying basin_index_fn = None but still facing the following error (attached below). Also I'm using this code to build the model:

> I'm also facing this error now: ValueError: The flow direction type could not be inferred.

On these two issues. It would be great to have a minimal reproducible example of your issue. Can you share your data,  hydromt-wflow configuration (ini) file, and data catalog file that return this error? Since this error seems to occur in the `[setup_basemaps]` step we only need the data used in that step.

> I downloaded the data for LAI from modis. Changed the variable name to "LAI" and ran the model but it gave this error. I'm confused on how to process the nc files in order to input it to the model. Can you tell me how to do it?

We use monthly climatology data for LAI. Your data seems to contain 87 timesteps? General information about preparing your data and renaming variables and setting the CRS in case it can not be inferred from the data is provided here https://deltares.github.io/hydromt/latest/user_guide/data_prepare_cat.html

**Comment by arsalansaghir1** [comment] 2023-03-08 07:05
I followed the data catalog instructions on the link you shared and prepared the yaml file shown below:
![Screenshot 2023-03-08 120227](https://user-images.githubusercontent.com/127018672/223642003-5648b52a-81c5-4bde-8549-026af8462ee4.jpg)

I am still facing the following error.
![Screenshot 2023-03-08 120306](https://user-images.githubusercontent.com/127018672/223642236-092dae76-74b1-417b-b17d-2e8369836616.jpg)

I downloaded the LAI data from the data source specified in documentation and it has following layers:
![Screenshot 2023-03-08 120443](https://user-images.githubusercontent.com/127018672/223642763-719c9eae-877b-4296-a6ee-b4b24349b6a0.jpg)

How to proceed with this?

**Comment by arsalansaghir1** [comment] 2023-03-08 13:04
It would really help if you could respond sooner. Thank you

**Comment by DirkEilander** [comment] 2023-03-08 14:20
Dear @arsalansaghir1, we're happy with your feedback and would like to help. However, outside of projects we don't have the capacity for on demand support. Is this work part of a project with Deltares? If you send me an email (dirk.eilander[at]deltares.nl) describing your needs I'm happy to discuss / set up a call how we can best support you. 

A few quick answers:
> I downloaded the LAI data from the data source specified. How to proceed with this?

As mentioned in an earlier reply this data needs to be processed to monthly mean climatology. That's easiest done in google earth engine (GEE) before downloading. It is on our radar (see #157) to describe the required preprocessing steps better. Any data pre-processing scripts and data downloads are currently out of scope for this package (also due to licences on various data sources) but can be discussed on a case to case basis.

> I am still facing the following error. [CRS is invalid red.]

This error is raised because somehow the Wflow model schematization you are preparing does not have a CRS. To understand why this occurs it would be useful if you can share a minimal reproducible example, as asked before. That means sharing a snippet of the data, hydromt-wflow configuration (ini) file, and data catalog (yml) file that return this error? Together with the output of running `conda list` form command line to see which versions of packages you are using.

**Comment by arsalansaghir1** [comment] 2023-03-08 17:38
Could you provide more detailed information on how to process the data to monthly mean climatology using GEE.? Also if some scripts could be provided for pre processing of data, that would be really helpful.

**Closed** 2023-07-27 09:51 UTC
Labels: bug, setup methods
